#!/usr/bin/python3
#parse.py

import urllib3
from urllib.request import urlopen
from bs4 import BeautifulSoup

url = urlopen("http://www.southwest.com")

page = url.read()
soup = BeautifulSoup(page, features="html.parser")

print(soup)
